
frameworkVersion: '2'

plugins:
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

